title: "Guilherme Franco - Matemática"
author: "Guilherme Franco"
description: "Site para publicar trabalhos e artigos, além de outros resultados interessantes que estudo."
permalink: /:title/
lang: "pt"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false      # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: true        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html", icon: home}
  - {file: "index.md", title: Anotações, icon: pen-to-square}
  - {file: "README.md", title: Sobre mim, icon: address-card}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: E-mail, icon: envelope, url: "mailto:limint@ufmg.br"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
